name: Git Inspector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inspect:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python
      run: sudo apt -y install python
    - name: Install gitinspector
      run: | 
        pushd ~ &> /dev/null
        git clone https://github.com/ejwa/gitinspector.git
        cd gitinspector
        echo "export PATH=$(pwd):"'$PATH' >> ~/.profile
        popd &> /dev/null
    - name: Run gitinspector
      run: |
        source ~/.profile
        export PYTHONIOENCODING=utf-8
        gitinspector.py --version
        echo "============ Git Inspector ==========="
        gitinspector.py -wTHl --format=text -f c,h,md,yml,* .
        echo "======================================"
